displayName: Node.js Serverless Function
description: An OpenShift Serverless Function in Node.js
tags: ["Node.js", "Serverless", "Function"]
globalMemoryLimit: 2674Mi
icon: https://avatars2.githubusercontent.com/u/44449734?s=400&u=2f5f9176b06feaa4f18218355052210d2fb72af7&v=4
projectType: "Node.js Function"
language: "Node.js"